development:
  adapter: postgresql
  host: localhost
  database: ruby_forms_db_dev
  username: ruby_forms_user
  password: 945ghriek

test:
  adapter: postgresql
  host: localhost
  database: ruby_forms_db_test
  username: ruby_forms_user
  password: 945ghriek

production:
  adapter: postgresql
  host: shdb.rad.jhmi.edu
  database: ruby_forms_db
  username: ruby_forms_user
  password: 945ghriek
